name: Deploy to UAT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version

      - name: Authenticate UAT Org
        run: |
          echo "${{ secrets.UAT_AUTH_URL }}" > authfile.txt
          sf org login sfdx-url \
            --sfdx-url-file authfile.txt \
            --alias uatOrg

      - name: Deploy Metadata
        run: |
          sf project deploy start \
            --target-org uatOrg \
            --source-dir force-app \
            --wait 60