name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version

      - name: Authenticate Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > authfile.txt
          sf org login sfdx-url \
            --sfdx-url-file authfile.txt \
            --alias targetOrg

      - name: Deploy Metadata
        run: |
          sf project deploy start \
            --target-org targetOrg \
            --source-dir force-app